
export const list = [
  {
    id: 1,
    title: "Poha",
    price: 10,
    img: "img/poha.jpg",
    amount: 1,
    kind: "Break-Fast",
  },
  {
    id: 2,
    title: "Upma",
    price: 15,
    img: "img/upama.jpg",
    amount: 1,
    kind: "Break-Fast",
  },
  {
    id: 3,
    title: "Samosa",
    price: 18,
    img: "img/samosa.jpg",
    amount: 1,
    kind: "Break-Fast",
  },
  {
    id: 4,
    title: "Kachori",
    price: 15,
    img: "img/kachori.jpg",
    amount: 1,
    kind: "Break-Fast",
  },
  {
    id: 5,
    title: "Aloo Vada",
    price: 15,
    img: "img/aloovada.jpg",
    amount: 1,
    kind: "Break-Fast",
  },
  {
    id: 6,
    title: "Dhokla",
    price: 15,
    img: "img/dhokala.jpg",
    amount: 1,
    kind: "Break-Fast",
  },
  {
    id: 7,
    title: "Sabudana Usal",
    price: 15,
    img: "img/sabudann.jpg",
    amount: 1,
    kind: "Break-Fast",
  },
  {
    id: 8,
    title: "Tea",
    price: 5,
    img: "img/tea.jpg",
    amount: 1,
    kind: "Beverages",
  },
  {
    id: 9,
    title: "Coffee",
    price: 8,
    img: "img/coffee.webp",
    amount: 1,
    kind: "Beverages",
  },
  {
    id: 10,
    title: "Milk",
    price: 7,
    img: "img/milk.webp",
    amount: 1,
    kind: "Beverages",
  },
  {
    id: 11,
    title: "Born-vita Milk",
    price: 15,
    img: "img/bornvita.jpg",
    amount: 1,
    kind: "Beverages",
  },
  {
    id: 12,
    title: "Lassi",
    price: 18,
    img: "img/lassi.jpg",
    amount: 1,
    kind: "Beverages",
  },
  {
    id: 13,
    title: "Parale-G",
    price: 5,
    img: "img/paraleg.webp",
    amount: 1,
    kind: "Biscuit",
  },
  {
    id: 14,
    title: "Happy Happy",
    price: 5,
    img: "img/happyhappy.jpg",
    amount: 1,
    kind: "Biscuit",
  },
  {
    id: 15,
    title: "Good Day",
    price: 5,
    img: "img/goodday.jpg",
    amount: 1,
    kind: "Biscuit",
  },
  {
    id: 16,
    title: "Monaco",
    price: 5,
    img: "img/monaco.jpeg",
    amount: 1,
    kind: "Biscuit",
  },
  // {
  //   id: 17,
  //   title: "African Salad Abacha",
  //   price: 1400,
  //   img: "img/african 8.jpeg",
  //   amount: 1,
  //   kind: "African",
  // },
  // {
  //   id: 18,
  //   title: "Kung Pao chicken",
  //   price: 2000,
  //   img: "img/chinese 5.jpeg",
  //   amount: 1,
  //   kind: "Chinese",
  // },
  // {
  //   id: 19,
  //   title: "Pancakes",
  //   price: 1300,
  //   img: "img/american 6.jpeg",
  //   amount: 1,
  //   kind: "America",
  // },
  // {
  //   id: 20,
  //   title: "Gatsby Sandwich",
  //   price: 1700,
  //   img: "img/african 10.jpg",
  //   amount: 1,
  //   kind: "African",
  // },
];
